# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7948b8b2e3df67c396b410c68350931fcdea7b6ba67cc5b006b8d843a0d7ee8438baef411e0628dbf5eedd10791f448498478d3a0bdf0d30c8009bd5d997b855

test:
  secret_key_base: 41f9ed59dddd28c5d5e18e816856bd54882c9dc3103b47433c8c043780a13bef4b98f25c8eb72db207f8cc5719f25a55bf31d332d9edae7bda56e1768c369d22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
